import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { zomatofeatures } from '../data.js'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      {/* banner for logout user */}
      <div className='banner'>
         <div className={styles.banner}>
             <div className={styles.header}>
                 <div className='header-left-section'>
                 <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" style={{"height":"15px"}} viewBox="0 0 384 512"><path d="M304 0h-224c-35.35 0-64 28.65-64 64v384c0 35.35 28.65 64 64 64h224c35.35 0 64-28.65 64-64V64C368 28.65 339.3 0 304 0zM192 480c-17.75 0-32-14.25-32-32s14.25-32 32-32s32 14.25 32 32S209.8 480 192 480zM304 64v320h-224V64H304z"/></svg>
                 <span className={styles.apptext}>Get The App</span>
                 </div>
                 <div className='header-right-section'>
                   <nav>
                      <ul className={styles.nav}>
                        <li>
                          <Link href="#">Investor Relations</Link>
                        </li>
                        <li>
                          <Link href="#">Add restaurant</Link>
                        </li>
                        <li>
                          <Link href="#">Log in</Link>
                        </li>
                        <li>
                          <Link href="#">Sign up</Link>
                        </li>
                      </ul>
                   </nav>
                 </div>
             </div>
             <div className={styles.bannermidtag}>
             <div className={styles.bannerlogo}>
              {/* <Image src="https://b.zmtcdn.com/web_assets/8313a97515fcb0447d2d77c276532a511583262271.png" layout="fill" objectFit='contain' alt="bannerlogo" /> */}
              <h1 className={styles.zomatotag}>ZOMATO</h1>
              <p className={styles.discovertag}>Discover the best food & drinks in </p>
              <div className={styles.zomatoloactionsearch}>
                  <div className={styles.zomatoloactioncontainer}>
                      <div className={styles.zomatoloaction}>
                          <svg xmlns="http://www.w3.org/2000/svg" className={styles.location} fill="#FF7E8B" width="20" height="20" viewBox="0 0 20 20" aria-labelledby="icon-svg-title- icon-svg-desc-" role="img"><title>location-fill</title><path d="M10.2 0.42c-4.5 0-8.2 3.7-8.2 8.3 0 6.2 7.5 11.3 7.8 11.6 0.2 0.1 0.3 0.1 0.4 0.1s0.3 0 0.4-0.1c0.3-0.2 7.8-5.3 7.8-11.6 0.1-4.6-3.6-8.3-8.2-8.3zM10.2 11.42c-1.7 0-3-1.3-3-3s1.3-3 3-3c1.7 0 3 1.3 3 3s-1.3 3-3 3z"></path></svg>
                          <input type="text" placeholder="Location" />
                          <svg xmlns="http://www.w3.org/2000/svg" fill="#4F4F4F" width="12" height="12" viewBox="0 0 20 20" aria-labelledby="icon-svg-title- icon-svg-desc-" role="img"><title>down-triangle</title><path d="M20 5.42l-10 10-10-10h20z"></path></svg>
                      </div>
                      <div className={styles.zomatosearchcontainer}> 
                        <div className={styles.zomatosearch}>
                        <div className={styles.linebar}></div>
                        <svg xmlns="http://www.w3.org/2000/svg" className={styles.search} fill="#828282" width="18" height="18" viewBox="0 0 20 20" aria-labelledby="icon-svg-title- icon-svg-desc-" role="img"><title>Search</title><path d="M19.78 19.12l-3.88-3.9c1.28-1.6 2.080-3.6 2.080-5.8 0-5-3.98-9-8.98-9s-9 4-9 9c0 5 4 9 9 9 2.2 0 4.2-0.8 5.8-2.1l3.88 3.9c0.1 0.1 0.3 0.2 0.5 0.2s0.4-0.1 0.5-0.2c0.4-0.3 0.4-0.8 0.1-1.1zM1.5 9.42c0-4.1 3.4-7.5 7.5-7.5s7.48 3.4 7.48 7.5-3.38 7.5-7.48 7.5c-4.1 0-7.5-3.4-7.5-7.5z"></path></svg>
                        <input type="text" placeholder="Search for restaurant, cuisine or a dish " />  
                        </div>
                      </div>
                  </div>
                  <div className={styles.zomatosearch}>
                    
                  </div>
              </div>
             </div>
         </div>
         </div>
      </div>
      {/* banner for logout user */}

      {/* zomato feature start */}
      <div className={styles.zomatofeature}>
          <div className={styles.zomatofeaturecontainer}>
              {
                zomatofeatures && zomatofeatures.map((feature,i) => (
                  <div className={styles.zomatofeatureboxes} key={i}>
                    <Image src={feature.image} alt={feature.description} layout="fill" />
                      <div className={styles.zomatofeaturetext}>
                          <p className={styles.zomatofeaturetitle}>{feature.title}</p>
                          <span className={styles.zomatofeaturedescription}>{feature.description}</span>
                      </div>
                  </div>
                ))
              }
          </div>
      </div>
      {/* zomato feature end */}

       {/* collection start */}
       <div className={styles.collection}>

       </div>
       {/* collection end */}

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
