import React, {useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
function mobile() {
    const [emailshow,setEmailshow] = useState(true);

    const handlesetEmail = (e) => {
      if(e.target.checked){
        setEmailshow(true)
      }
      
    }
    const handlesetPhone = (e) => { 
      if(e.target.checked){
        setEmailshow(false)
      }
      
     }
  return (
    <div>
        <Head>
        <title>Zomato mobile App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
            <div className={styles.downloadappimage}>
                 <Image src="https://b.zmtcdn.com/web_assets/b40b97e677bc7b2ca77c58c61db266fe1603954218.png" width={150} height={40} layout="responsive" alt="bannerlogo" />
            </div>
            <div>
            <nav>
                      <ul className={styles.mobilesection}>
                        <li className={styles.mobilelog}>
                          <Link href="#">Log in</Link>
                        </li>
                        <li className={styles.mobilesignin}>
                          <Link href="#">Sign up</Link>
                        </li>
                      </ul>
                   </nav>
             </div>
                   
        </header>

        {/* Zomato app start */}

        <div className={styles.zomatoapps}>
            <div className={styles.zomatoappcontainer}>
                 <div className={styles.zomatoappimagebox}>
                     <img src="https://b.zmtcdn.com/data/o2_assets/a500ffc2ab483bc6a550aa635f4e55531648107832.png" alt="zomatoapp" />
                 </div>
                 <div className={styles.zomatoapptextbox}>
                     <h2>Get the Zomato app</h2>
                     <p>We will send you a link, open it on your phone to download the app</p>
                     <div className={styles.radiobutton}>
                        <label className={styles.labelemail}>
                            <input type="radio" name="radiobutton" value="email" className={styles.radiobuttonselect} onChange={handlesetEmail} />
                            { emailshow === true  && <svg viewBox="0 0 20 20" className="sc-djusq7-2 ctMLcL"><circle cx="10" cy="10" r="8" name="radio" value="email" label="Email" checked="" className="sc-djusq7-3 bIgyOk" stroke="rgb(239, 79, 95)" strokeWidth="1px" fill="rgb(255, 255, 255)"></circle><circle cx="10" cy="10" r="5" name="radio" value="email" label="Email" className="sc-djusq7-4 hLkMFn" fill="rgb(239, 79, 95)"></circle></svg> }
                            <span>Email</span>
                        </label>
                        <label className={styles.labelphone}>
                            <input type="radio" name="radiobutton" value="email" className={styles.radiobuttonselect} onChange={handlesetPhone} />
                            { emailshow === false  && <svg viewBox="0 0 20 20" className="sc-djusq7-2 ctMLcL"><circle cx="10" cy="10" r="8" name="radio" value="email" label="Email" checked="" className="sc-djusq7-3 bIgyOk" stroke="rgb(239, 79, 95)" strokeWidth="1px" fill="rgb(255, 255, 255)"></circle><circle cx="10" cy="10" r="5" name="radio" value="email" label="Email" className="sc-djusq7-4 hLkMFn" fill="rgb(239, 79, 95)"></circle></svg> }
                            <span>Phone</span>
                        </label>
                     </div>
                     <div className={styles.emailphonebox}>
                         <div className={styles.emailphoneboxcontainer}>
                             <form>
                                {
                                  emailshow === true && <input type="text" className={styles.emailphoneboxinput} placeholder="Email" name="email" />
                                }
                                {
                                  emailshow === false && <input type="text" className={styles.emailphoneboxinput} placeholder='Phone' name="phone" />
                                }
                                 <button type="submit" className={styles.shareapplink}>Share App Link</button>
                             </form>
                             <span className={styles.downloadapp}>Download app from</span>
                             <div className={styles.downloadappbox}>
                              <div className={styles.downloadappimage}><Image src="https://b.zmtcdn.com/data/webuikit/9f0c85a5e33adb783fa0aef667075f9e1556003622.png" width={150} height={40} layout="responsive" alt="downloadapp" /></div>
                              <div className={styles.downloadappimage}><Image src="https://b.zmtcdn.com/data/webuikit/23e930757c3df49840c482a8638bf5c31556001144.png" width={150} height={40} layout="responsive" alt="downloadapp" /></div>
                             </div>
                         </div>
                     </div>
                 </div>
            </div>
        </div>

       {/* Zomato app end */}
    </div>
  )
}

export default mobile